name: Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  release-crates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: publish package to crates
        run: |
          cargo package
          cargo publish --token ${{ secrets.CARGO_TOKEN }}

  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: cargo build --release
      - name: archive
        run: |
          GIT_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          tar -C target/release -czf $(pwd)/cargo-tarpaulin-${GIT_TAG}-travis.tar.gz cargo-tarpaulin
      - name: publish release
        uses: softprops/action-gh-release@v1
        with:
          files: cargo-tarpaulin-*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
